# 05-gotrue.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotrue
  namespace: appflowy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotrue
  template:
    metadata:
      labels:
        app: gotrue
    spec:
      containers:
        - name: gotrue
          image: appflowyinc/gotrue:latest
          env:
            - name: GOTRUE_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: appflowy-cloud-secrets
                  key: gotrue-admin-email
            - name: GOTRUE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appflowy-cloud-secrets
                  key: gotrue-admin-password
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: appflowy-cloud-secrets
                  key: gotrue-jwt-secret
            - name: GOTRUE_JWT_EXP
              value: "604800"
            - name: GOTRUE_DISABLE_SIGNUP
              valueFrom:
                configMapKeyRef:
                  name: appflowy-cloud-config
                  key: GOTRUE_DISABLE_SIGNUP
            - name: GOTRUE_MAILER_AUTOCONFIRM
              valueFrom:
                configMapKeyRef:
                  name: appflowy-cloud-config
                  key: GOTRUE_MAILER_AUTOCONFIRM
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/appflowy?search_path=auth"
            - name: API_EXTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: appflowy-cloud-config
                  key: APPFLOWY_BASE_URL
              value: "https://appflowy.triggeriq.eu/gotrue"
            - name: PORT
              value: "9999"
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: gotrue
  namespace: appflowy
spec:
  selector:
    app: gotrue
  ports:
    - port: 9999
      targetPort: 9999